# Generated by Django 6.1.1 on 2026-09-15 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='Vehicle_type',
            new_name='vehicle_type',
        ),
        migrations.RenameField(
            model_name='vehicleimage',
            old_name='Image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='vehicleimage',
            old_name='Vehicle',
            new_name='vehicle',
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='vehicleimage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
